/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public String getSum(int x, int y) {
    return "Sum of " + x + " and " + y + " is " + new Calculate().sum(x, y) + ". Average is "
        + new Calculate().average(x, y) + ".";
  }

  public String getSigma(int x, int y) {
    return "Sum of " + x + " to " + y + " is " + new Calculate().sigma(x, y) + ". Average is "
        + new Calculate().average(x, y) + ".";
  }

  public String getOden(int x, int y) {
    return "Sum of odd of " + x + " to " + y + " is " + new Calculate().odd(x, y) + ". Sum of even is "
        + new Calculate().even(x, y)
        + ".";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println(
        new App().getSum(2, 3));
    System.out.println(
        new App().getSigma(1, 10));
    System.out.println(new App().getOden(1, 10));
  }
}
